### ISSUE TITLE
vdsm-jsonrpc-java Connecting error

### ISSUE THREAD

**Issue by midieyz** [oVirt/vdsm-jsonrpc-java#25]
bro, help!
version: ovirt **4.3.10**,  vdsm-jsonrpc-java-client **1.4.18**

result error:
 2022-10-27 11:15:56.163  INFO 5696 --- [  Stomp Reactor] o.o.v.j.client.reactors.ReactorClient    : Connecting to /10.42.200.63
2022-10-27 11:15:56.170 ERROR 5696 --- [  Stomp Reactor] o.o.v.jsonrpc.client.reactors.Reactor    : Unable to process messages 远程主机强迫关闭了一个现有的连接。
<JsonRpcResponse id: null error: {"code":5022,"message":"远程主机强迫关闭了一个现有的连接。"}>

test code: 
`  String hostName = "10.42.200.63";
        int port = 54321;
        int clientTimeout = 100000;
        int connectionRetry = 0;
        int heartbeat = 3000;
        int parallelism = 30000;
        int eventTimeoutInHours = 100000;
        int connectionTimeout =300000;
        String eventQueue = "queue";
        ScheduledExecutorService executorService = new ScheduledThreadPoolExecutor(1);
        StompClientPolicy connectionPolicy =
                new StompClientPolicy(connectionTimeout,
                        connectionRetry,
                        heartbeat,
                        IOException.class,
                        DEFAULT_REQUEST_QUEUE,
                        DEFAULT_RESPONSE_QUEUE);
        connectionPolicy.setEventQueue(eventQueue);
        ClientPolicy clientPolicy = new ClientPolicy(clientTimeout, connectionRetry, heartbeat, IOException.class);

        final Reactor reactor = ReactorFactory.getReactor(null, ReactorType.STOMP);
        final ReactorClient client = reactor.createClient(hostName, port);

        client.setClientPolicy(connectionPolicy);
        ResponseWorker worker = ReactorFactory.getWorker(parallelism, eventTimeoutInHours);
        JsonRpcClient jsonClient = worker.register(client);
        jsonClient.setRetryPolicy(clientPolicy);
        jsonClient.setExecutorService(executorService);

        JsonRpcRequest request = new RequestBuilder("Host.getCapabilities").build();
        Future<JsonRpcResponse> call = jsonClient.call(request);
        JsonRpcResponse jsonRpcResponse = call.get();
        System.out.println(jsonRpcResponse);
 `

**Comment by sandrobonazzola** [comment]
Closing as 4.3 gone EOL long time ago. Please upgrade to latest oVirt release and if problem still exists please open a new issue.
